### PR TITLE
Rpm5 stuff

### PR DESCRIPTION
**Pull request by proyvind**
here's some work, where most importantly is to add the %_specfile macro which while implemented @rpm5.org, it's not implemented for rpmorg.

It also adds back support %{python:} in package spec files.

### CODE REVIEW

**Comment by tpgxyz** [comment]
Why dot you prepare PR to upstream ?

I think we should avoid past situation and carry tons of patches mostly "being" here (mostly not used.).

**Comment by proyvind** [comment]
because the upstream PR hasn't really been concluded, despite taking over a year..

Meanwhile this is functionality derived from rpm5.org, for which there already are packages in the distro using this functionality.

**Comment by Conan-Kudo** [comment]
> Meanwhile this is functionality derived from rpm5.org, for which there already are packages in the distro using this functionality.

Not anymore. We've changed them to either execute python and use `%{expand:}` to force a reparsing of the spec, or we dropped the templating entirely.

**Comment by proyvind** [comment]
Which can't in any way be considered an improvement, can it?!?

**Pull request closed without merging**
